// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: mailbox_register.proto

/* eslint-disable */

export const protobufPackage = "mailboxregister";

export interface RunMailboxRegistrationRequest {
  enabled: boolean;
  import_only: boolean;
}

export interface RunMailboxRegistrationResponse {
  success: boolean;
  exit_code: number;
  error_message: string;
  accounts: MailboxRegistrationAccount[];
}

export interface MailboxRegistrationAccount {
  email_address: string;
  password: string;
  refresh_token: string;
  access_token: string;
  source: string;
}

export interface RunMailboxOAuthRequest {
  email_address: string;
  only_missing: boolean;
  limit: number;
  accounts: MailboxRegistrationAccount[];
}

export interface MailboxOAuthResult {
  email_address: string;
  success: boolean;
  error_message: string;
  refresh_token: string;
  access_token: string;
}

export interface RunMailboxOAuthResponse {
  success: boolean;
  processed: number;
  succeeded: number;
  failed: number;
  error_message: string;
  results: MailboxOAuthResult[];
}
