// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_mailbox.proto

/* eslint-disable */
import type { FetchMailboxInboxResult } from "./email";

export const protobufPackage = "orchestrator";

export interface RegisteredMailboxResult {
  email_address: string;
  status: string;
}

export interface MailboxRegistrationActivityInput {
  job_id: string;
  enabled: boolean;
  import_only: boolean;
}

export interface MailboxRegistrationActivityOutput {
  success: boolean;
  exit_code: number;
  error_message: string;
  mailboxes: RegisteredMailboxResult[];
  data: { [key: string]: any } | undefined;
}

export interface MailboxOAuthActivityInput {
  job_id: string;
  email_address: string;
  only_missing: boolean;
  limit: number;
}

export interface MailboxOAuthActivityOutput {
  success: boolean;
  processed: number;
  succeeded: number;
  failed: number;
  error_message: string;
  data: { [key: string]: any } | undefined;
}

export interface RegisterMailboxRequest {
  import_only: boolean;
}

export interface RegisterMailboxResponse {
  job_id: string;
  success: boolean;
  exit_code: number;
  error_message: string;
  mailboxes: RegisteredMailbox[];
}

export interface RegisteredMailbox {
  email_address: string;
  password: string;
  refresh_token: string;
  access_token: string;
  status: string;
}

export interface StartMailboxOAuthRequest {
  email_address: string;
  only_missing: boolean;
  limit: number;
}

export interface StartMailboxOAuthResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface FetchMailboxInboxesRequest {
  limit_per_mailbox: number;
  max_mailboxes: number;
  email_address: string;
}

export interface MailboxBanDetection {
  account_id: string;
  email_address: string;
  mailbox_email: string;
  from_address: string;
  subject: string;
  received_at_unix: number;
  account_updated: boolean;
  error_message: string;
}

export interface FetchMailboxInboxesResponse {
  results: FetchMailboxInboxResult[];
  mailbox_count: number;
  fetched_count: number;
  failed_count: number;
  message_count: number;
  bans: MailboxBanDetection[];
  ban_count: number;
}

export interface RegisterMailboxWorkflowInput {
  job_id: string;
  import_only: boolean;
  auto_oauth: boolean;
}

export interface RegisterMailboxWorkflowResult {
  job_id: string;
  success: boolean;
  exit_code: number;
  error_message: string;
  mailboxes: RegisteredMailboxResult[];
}

export interface MailboxOAuthWorkflowInput {
  job_id: string;
  email_address: string;
  only_missing: boolean;
  limit: number;
}

export interface MailboxOAuthWorkflowResult {
  job_id: string;
  success: boolean;
  processed: number;
  succeeded: number;
  failed: number;
  error_message: string;
}
